name: noteapp_note_query_service
version: "0.1.0"
author: CG  <abc@abc.com>
about: Note App
args:
    - domain:
        short: d
        long: domain
        env: DOMAIN
        value_name: Domain
        required: true
        about: Sets domain of microservice
        default_value: 127.0.0.1
        takes_value: true
    - port:
        short: o
        long: port
        env: SERVICE_PORT
        value_name: PORT
        required: true
        about: Sets port of microservice
        default_value: "8080"
        takes_value: true
    - kafka-brokers-addr:
        short: b
        long: kafka-brokers-addr
        env: KAFKA_BROKERS_ADDR
        value_name: KAFKA_BROKERS_ADDR
        required: true
        default_value: localhost:9092
        about: Sets address of kafka brokers
        takes_value: true
    - kafka-consumer-topics:
        short: t
        long: kafka-consumer-topics
        env: KAFKA_CONSUMER_TOPICS
        value_name: KAFKA_CONSUMER_TOPICS
        required: true
        default_value: note.command.service
        about: Sets consumer topics of kafka
        takes_value: true
    - mongodb-host:
        short: h
        long: mongodb-host
        env: MONGODB_HOST
        value_name: MONGODB_HOST
        required: true
        about: Sets host string of mongodb
        default_value: localhost:27017
        takes_value: true
    - mongodb-username:
        short: u
        long: mongodb-username
        env: MONGODB_USERNAME
        value_name: MONGODB_USERNAME
        required: true
        about: Sets username of mongodb
        default_value: admin
        takes_value: true
    - mongodb-password:
        short: p
        long: mongodb-password
        env: MONGODB_PASSWORD
        value_name: MONGODB_PASSWORD
        required: true
        about: Sets password of mongodb
        default_value: demo
        takes_value: true
    - mongodb-collection:
        short: c
        long: mongodb-collection
        env: MONGODB_COLLECTION
        value_name: MONGODB_COLLECTION
        required: true
        about: Sets collection of mongodb
        default_value: Notes
        takes_value: true